package nbt

// https://minecraft.fandom.com/wiki/NBT_format#TAG_definition

// TagType ...
type TagType byte

const (
	// TagEnd ...
	TagEnd TagType = iota
	// TagByte ...
	TagByte
	// TagShort ...
	TagShort
	// TagInt ...
	TagInt
	// TagLong ...
	TagLong
	// TagFloat ...
	TagFloat
	// TagDouble ...
	TagDouble
	// TagByteArray ...
	TagByteArray
	// TagString ...
	TagString
	//TagList ...
	TagList
	// TagCompound ...
	TagCompound
	// TagIntArray ...
	TagIntArray
	// TagLongArray ...
	TagLongArray
)
