package mc

import (
	"fmt"
	"strings"
)

type ID string

func (i ID) String() string {
	trimmed := strings.TrimPrefix(string(i), "minecraft:")
	return fmt.Sprintf("[ID:%s]", trimmed)
}

const (
	AcaciaBoatID                    = "minecraft:acacia_boat"
	AcaciaButtonID                  = "minecraft:acacia_button"
	AcaciaDoorID                    = "minecraft:acacia_door"
	AcaciaFenceID                   = "minecraft:acacia_fence"
	AcaciaLogID                     = "minecraft:acacia_log"
	AcaciaPlanksID                  = "minecraft:acacia_planks"
	AcaciaSaplingID                 = "minecraft:acacia_sapling"
	AcaciaSlabID                    = "minecraft:acacia_slab"
	AcaciaStairsID                  = "minecraft:acacia_stairs"
	AcaciaTrapdoorID                = "minecraft:acacia_trapdoor"
	AcaciaWoodID                    = "minecraft:acacia_wood"
	ActivatorRailID                 = "minecraft:activator_rail"
	AlliumID                        = "minecraft:allium"
	AmethystBlockID                 = "minecraft:amethyst_block"
	AmethystClusterID               = "minecraft:amethyst_cluster"
	AmethystShardID                 = "minecraft:amethyst_shard"
	AncientDebrisID                 = "minecraft:ancient_debris"
	AndesiteID                      = "minecraft:andesite"
	AndesiteSlabID                  = "minecraft:andesite_slab"
	AndesiteStairsID                = "minecraft:andesite_stairs"
	AndesiteWallID                  = "minecraft:andesite_wall"
	AnvilID                         = "minecraft:anvil"
	ArmorStandID                    = "minecraft:armor_stand"
	ArrowID                         = "minecraft:arrow"
	AxolotlBucketID                 = "minecraft:axolotl_bucket"
	AzaleaID                        = "minecraft:azalea"
	AzaleaLeavesID                  = "minecraft:azalea_leaves"
	AzureBluetID                    = "minecraft:azure_bluet"
	BambooID                        = "minecraft:bamboo"
	BasaltID                        = "minecraft:basalt"
	BeaconID                        = "minecraft:beacon"
	BeeNestID                       = "minecraft:bee_nest"
	BeefID                          = "minecraft:beef"
	BeetrootSeedsID                 = "minecraft:beetroot_seeds"
	BigDripleafID                   = "minecraft:big_dripleaf"
	BirchBoatID                     = "minecraft:birch_boat"
	BirchButtonID                   = "minecraft:birch_button"
	BirchFenceID                    = "minecraft:birch_fence"
	BirchLeavesID                   = "minecraft:birch_leaves"
	BirchLogID                      = "minecraft:birch_log"
	BirchPlanksID                   = "minecraft:birch_planks"
	BirchSaplingID                  = "minecraft:birch_sapling"
	BirchSignID                     = "minecraft:birch_sign"
	BirchSlabID                     = "minecraft:birch_slab"
	BirchTrapdoorID                 = "minecraft:birch_trapdoor"
	BlackConcreteID                 = "minecraft:black_concrete"
	BlackDyeID                      = "minecraft:black_dye"
	BlackShulkerBoxID               = "minecraft:black_shulker_box"
	BlackStainedGlassID             = "minecraft:black_stained_glass"
	BlackStainedGlassPaneID         = "minecraft:black_stained_glass_pane"
	BlackTerracottaID               = "minecraft:black_terracotta"
	BlackWoolID                     = "minecraft:black_wool"
	BlackstoneID                    = "minecraft:blackstone"
	BlackstoneSlabID                = "minecraft:blackstone_slab"
	BlackstoneStairsID              = "minecraft:blackstone_stairs"
	BlackstoneWallID                = "minecraft:blackstone_wall"
	BlastFurnaceID                  = "minecraft:blast_furnace"
	BlazePowderID                   = "minecraft:blaze_powder"
	BlazeRodID                      = "minecraft:blaze_rod"
	BlueCarpetID                    = "minecraft:blue_carpet"
	BlueConcreteID                  = "minecraft:blue_concrete"
	BlueDyeID                       = "minecraft:blue_dye"
	BlueGlazedTerracottaID          = "minecraft:blue_glazed_terracotta"
	BlueIceID                       = "minecraft:blue_ice"
	BlueOrchidID                    = "minecraft:blue_orchid"
	BlueShulkerBoxID                = "minecraft:blue_shulker_box"
	BlueStainedGlassID              = "minecraft:blue_stained_glass"
	BlueStainedGlassPaneID          = "minecraft:blue_stained_glass_pane"
	BlueTerracottaID                = "minecraft:blue_terracotta"
	BlueWoolID                      = "minecraft:blue_wool"
	BoneID                          = "minecraft:bone"
	BoneBlockID                     = "minecraft:bone_block"
	BoneMealID                      = "minecraft:bone_meal"
	BookshelfID                     = "minecraft:bookshelf"
	BowID                           = "minecraft:bow"
	BowlID                          = "minecraft:bowl"
	BrainCoralID                    = "minecraft:brain_coral"
	BrainCoralBlockID               = "minecraft:brain_coral_block"
	BrainCoralFanID                 = "minecraft:brain_coral_fan"
	BrewingStandID                  = "minecraft:brewing_stand"
	BrickID                         = "minecraft:brick"
	BrickSlabID                     = "minecraft:brick_slab"
	BrickStairsID                   = "minecraft:brick_stairs"
	BrickWallID                     = "minecraft:brick_wall"
	BricksID                        = "minecraft:bricks"
	BrownCarpetID                   = "minecraft:brown_carpet"
	BrownDyeID                      = "minecraft:brown_dye"
	BrownMushroomID                 = "minecraft:brown_mushroom"
	BrownMushroomBlockID            = "minecraft:brown_mushroom_block"
	BrownShulkerBoxID               = "minecraft:brown_shulker_box"
	BrownStainedGlassID             = "minecraft:brown_stained_glass"
	BrownStainedGlassPaneID         = "minecraft:brown_stained_glass_pane"
	BrownWoolID                     = "minecraft:brown_wool"
	BubbleCoralID                   = "minecraft:bubble_coral"
	BubbleCoralBlockID              = "minecraft:bubble_coral_block"
	BubbleCoralFanID                = "minecraft:bubble_coral_fan"
	BucketID                        = "minecraft:bucket"
	CalciteID                       = "minecraft:calcite"
	CampfireID                      = "minecraft:campfire"
	CarrotID                        = "minecraft:carrot"
	CarrotOnAStickID                = "minecraft:carrot_on_a_stick"
	CartographyTableID              = "minecraft:cartography_table"
	CarvedPumpkinID                 = "minecraft:carved_pumpkin"
	CauldronID                      = "minecraft:cauldron"
	ChainID                         = "minecraft:chain"
	ChainmailBootsID                = "minecraft:chainmail_boots"
	ChainmailChestplateID           = "minecraft:chainmail_chestplate"
	ChainmailHelmetID               = "minecraft:chainmail_helmet"
	ChainmailLeggingsID             = "minecraft:chainmail_leggings"
	CharcoalID                      = "minecraft:charcoal"
	ChiseledDeepslateID             = "minecraft:chiseled_deepslate"
	ChiseledPolishedBlackstoneID    = "minecraft:chiseled_polished_blackstone"
	ChiseledQuartzBlockID           = "minecraft:chiseled_quartz_block"
	ChiseledSandstoneID             = "minecraft:chiseled_sandstone"
	ChiseledStoneBricksID           = "minecraft:chiseled_stone_bricks"
	ChorusFlowerID                  = "minecraft:chorus_flower"
	ChorusFruitID                   = "minecraft:chorus_fruit"
	ClayID                          = "minecraft:clay"
	ClayBallID                      = "minecraft:clay_ball"
	ClockID                         = "minecraft:clock"
	CoalID                          = "minecraft:coal"
	CoalBlockID                     = "minecraft:coal_block"
	CoalOreID                       = "minecraft:coal_ore"
	CoarseDirtID                    = "minecraft:coarse_dirt"
	CobbledDeepslateID              = "minecraft:cobbled_deepslate"
	CobbledDeepslateSlabID          = "minecraft:cobbled_deepslate_slab"
	CobbledDeepslateWallID          = "minecraft:cobbled_deepslate_wall"
	CobblestoneID                   = "minecraft:cobblestone"
	CobblestoneSlabID               = "minecraft:cobblestone_slab"
	CobblestoneStairsID             = "minecraft:cobblestone_stairs"
	CobblestoneWallID               = "minecraft:cobblestone_wall"
	CobwebID                        = "minecraft:cobweb"
	CocoaBeansID                    = "minecraft:cocoa_beans"
	ComparatorID                    = "minecraft:comparator"
	CompassID                       = "minecraft:compass"
	ComposterID                     = "minecraft:composter"
	ConduitID                       = "minecraft:conduit"
	CookedBeefID                    = "minecraft:cooked_beef"
	CookedChickenID                 = "minecraft:cooked_chicken"
	CookedCodID                     = "minecraft:cooked_cod"
	CookedMuttonID                  = "minecraft:cooked_mutton"
	CookieID                        = "minecraft:cookie"
	CopperIngotID                   = "minecraft:copper_ingot"
	CopperOreID                     = "minecraft:copper_ore"
	CornflowerID                    = "minecraft:cornflower"
	CrackedStoneBricksID            = "minecraft:cracked_stone_bricks"
	CraftingTableID                 = "minecraft:crafting_table"
	CreeperHeadID                   = "minecraft:creeper_head"
	CrimsonDoorID                   = "minecraft:crimson_door"
	CrimsonFenceID                  = "minecraft:crimson_fence"
	CrimsonFungusID                 = "minecraft:crimson_fungus"
	CrimsonHyphaeID                 = "minecraft:crimson_hyphae"
	CrimsonNyliumID                 = "minecraft:crimson_nylium"
	CrimsonPlanksID                 = "minecraft:crimson_planks"
	CrimsonPressurePlateID          = "minecraft:crimson_pressure_plate"
	CrimsonRootsID                  = "minecraft:crimson_roots"
	CrimsonSlabID                   = "minecraft:crimson_slab"
	CrimsonStairsID                 = "minecraft:crimson_stairs"
	CrimsonStemID                   = "minecraft:crimson_stem"
	CrimsonTrapdoorID               = "minecraft:crimson_trapdoor"
	CrossbowID                      = "minecraft:crossbow"
	CryingObsidianID                = "minecraft:crying_obsidian"
	CutCopperID                     = "minecraft:cut_copper"
	CutCopperSlabID                 = "minecraft:cut_copper_slab"
	CutCopperStairsID               = "minecraft:cut_copper_stairs"
	CutRedSandstoneID               = "minecraft:cut_red_sandstone"
	CutRedSandstoneSlabID           = "minecraft:cut_red_sandstone_slab"
	CutSandstoneID                  = "minecraft:cut_sandstone"
	CutSandstoneSlabID              = "minecraft:cut_sandstone_slab"
	CyanCarpetID                    = "minecraft:cyan_carpet"
	CyanConcreteID                  = "minecraft:cyan_concrete"
	CyanDyeID                       = "minecraft:cyan_dye"
	CyanGlazedTerracottaID          = "minecraft:cyan_glazed_terracotta"
	CyanShulkerBoxID                = "minecraft:cyan_shulker_box"
	CyanStainedGlassID              = "minecraft:cyan_stained_glass"
	CyanStainedGlassPaneID          = "minecraft:cyan_stained_glass_pane"
	CyanTerracottaID                = "minecraft:cyan_terracotta"
	CyanWoolID                      = "minecraft:cyan_wool"
	DandelionID                     = "minecraft:dandelion"
	DarkOakBoatID                   = "minecraft:dark_oak_boat"
	DarkOakFenceID                  = "minecraft:dark_oak_fence"
	DarkOakFenceGateID              = "minecraft:dark_oak_fence_gate"
	DarkOakLeavesID                 = "minecraft:dark_oak_leaves"
	DarkOakLogID                    = "minecraft:dark_oak_log"
	DarkOakPlanksID                 = "minecraft:dark_oak_planks"
	DarkOakPressurePlateID          = "minecraft:dark_oak_pressure_plate"
	DarkOakSaplingID                = "minecraft:dark_oak_sapling"
	DarkOakSignID                   = "minecraft:dark_oak_sign"
	DarkOakSlabID                   = "minecraft:dark_oak_slab"
	DarkOakStairsID                 = "minecraft:dark_oak_stairs"
	DarkOakTrapdoorID               = "minecraft:dark_oak_trapdoor"
	DarkOakWoodID                   = "minecraft:dark_oak_wood"
	DarkPrismarineID                = "minecraft:dark_prismarine"
	DarkPrismarineSlabID            = "minecraft:dark_prismarine_slab"
	DarkPrismarineStairsID          = "minecraft:dark_prismarine_stairs"
	DaylightDetectorID              = "minecraft:daylight_detector"
	DeadBrainCoralBlockID           = "minecraft:dead_brain_coral_block"
	DeadBubbleCoralBlockID          = "minecraft:dead_bubble_coral_block"
	DeadFireCoralBlockID            = "minecraft:dead_fire_coral_block"
	DeadFireCoralFanID              = "minecraft:dead_fire_coral_fan"
	DeadHornCoralBlockID            = "minecraft:dead_horn_coral_block"
	DeadTubeCoralBlockID            = "minecraft:dead_tube_coral_block"
	DeepslateID                     = "minecraft:deepslate"
	DeepslateBrickSlabID            = "minecraft:deepslate_brick_slab"
	DeepslateBrickStairsID          = "minecraft:deepslate_brick_stairs"
	DeepslateBrickWallID            = "minecraft:deepslate_brick_wall"
	DeepslateBricksID               = "minecraft:deepslate_bricks"
	DeepslateCoalOreID              = "minecraft:deepslate_coal_ore"
	DeepslateCopperOreID            = "minecraft:deepslate_copper_ore"
	DeepslateDiamondOreID           = "minecraft:deepslate_diamond_ore"
	DeepslateGoldOreID              = "minecraft:deepslate_gold_ore"
	DeepslateIronOreID              = "minecraft:deepslate_iron_ore"
	DeepslateLapisOreID             = "minecraft:deepslate_lapis_ore"
	DeepslateRedstoneOreID          = "minecraft:deepslate_redstone_ore"
	DeepslateTileSlabID             = "minecraft:deepslate_tile_slab"
	DeepslateTileStairsID           = "minecraft:deepslate_tile_stairs"
	DeepslateTileWallID             = "minecraft:deepslate_tile_wall"
	DeepslateTilesID                = "minecraft:deepslate_tiles"
	DetectorRailID                  = "minecraft:detector_rail"
	DiamondID                       = "minecraft:diamond"
	DiamondBootsID                  = "minecraft:diamond_boots"
	DiamondHelmetID                 = "minecraft:diamond_helmet"
	DiamondHorseArmorID             = "minecraft:diamond_horse_armor"
	DiamondLeggingsID               = "minecraft:diamond_leggings"
	DiamondOreID                    = "minecraft:diamond_ore"
	DiamondPickaxeID                = "minecraft:diamond_pickaxe"
	DiamondShovelID                 = "minecraft:diamond_shovel"
	DiamondSwordID                  = "minecraft:diamond_sword"
	DioriteID                       = "minecraft:diorite"
	DioriteSlabID                   = "minecraft:diorite_slab"
	DioriteStairsID                 = "minecraft:diorite_stairs"
	DioriteWallID                   = "minecraft:diorite_wall"
	DirtID                          = "minecraft:dirt"
	DragonBreathID                  = "minecraft:dragon_breath"
	DragonHeadID                    = "minecraft:dragon_head"
	DripstoneBlockID                = "minecraft:dripstone_block"
	EggID                           = "minecraft:egg"
	ElytraID                        = "minecraft:elytra"
	EmeraldID                       = "minecraft:emerald"
	EmeraldOreID                    = "minecraft:emerald_ore"
	EnchantedGoldenAppleID          = "minecraft:enchanted_golden_apple"
	EnchantingTableID               = "minecraft:enchanting_table"
	EndCrystalID                    = "minecraft:end_crystal"
	EndGatewayID                    = "minecraft:end_gateway"
	EndPortalID                     = "minecraft:end_portal"
	EndRodID                        = "minecraft:end_rod"
	EndStoneID                      = "minecraft:end_stone"
	EndStoneBrickSlabID             = "minecraft:end_stone_brick_slab"
	EndStoneBrickStairsID           = "minecraft:end_stone_brick_stairs"
	EndStoneBricksID                = "minecraft:end_stone_bricks"
	EnderChestID                    = "minecraft:ender_chest"
	EnderPearlID                    = "minecraft:ender_pearl"
	ExperienceBottleID              = "minecraft:experience_bottle"
	FermentedSpiderEyeID            = "minecraft:fermented_spider_eye"
	FernID                          = "minecraft:fern"
	FilledMapID                     = "minecraft:filled_map"
	FireChargeID                    = "minecraft:fire_charge"
	FireCoralID                     = "minecraft:fire_coral"
	FireCoralBlockID                = "minecraft:fire_coral_block"
	FireCoralFanID                  = "minecraft:fire_coral_fan"
	FireballID                      = "minecraft:fireball"
	FireworkRocketID                = "minecraft:firework_rocket"
	FireworkStarID                  = "minecraft:firework_star"
	FishingRodID                    = "minecraft:fishing_rod"
	FletchingTableID                = "minecraft:fletching_table"
	FlintID                         = "minecraft:flint"
	FlintAndSteelID                 = "minecraft:flint_and_steel"
	FlowerPotID                     = "minecraft:flower_pot"
	FloweringAzaleaID               = "minecraft:flowering_azalea"
	FloweringAzaleaLeavesID         = "minecraft:flowering_azalea_leaves"
	GhastTearID                     = "minecraft:ghast_tear"
	GlassID                         = "minecraft:glass"
	GlassPaneID                     = "minecraft:glass_pane"
	GlisteringMelonSliceID          = "minecraft:glistering_melon_slice"
	GlowBerriesID                   = "minecraft:glow_berries"
	GlowInkSacID                    = "minecraft:glow_ink_sac"
	GlowLichenID                    = "minecraft:glow_lichen"
	GlowstoneID                     = "minecraft:glowstone"
	GlowstoneDustID                 = "minecraft:glowstone_dust"
	GoldBlockID                     = "minecraft:gold_block"
	GoldIngotID                     = "minecraft:gold_ingot"
	GoldNuggetID                    = "minecraft:gold_nugget"
	GoldOreID                       = "minecraft:gold_ore"
	GoldenAppleID                   = "minecraft:golden_apple"
	GoldenAxeID                     = "minecraft:golden_axe"
	GoldenBootsID                   = "minecraft:golden_boots"
	GoldenCarrotID                  = "minecraft:golden_carrot"
	GoldenChestplateID              = "minecraft:golden_chestplate"
	GoldenHelmetID                  = "minecraft:golden_helmet"
	GoldenHoeID                     = "minecraft:golden_hoe"
	GoldenHorseArmorID              = "minecraft:golden_horse_armor"
	GoldenLeggingsID                = "minecraft:golden_leggings"
	GoldenPickaxeID                 = "minecraft:golden_pickaxe"
	GoldenShovelID                  = "minecraft:golden_shovel"
	GoldenSwordID                   = "minecraft:golden_sword"
	GraniteSlabID                   = "minecraft:granite_slab"
	GraniteStairsID                 = "minecraft:granite_stairs"
	GraniteWallID                   = "minecraft:granite_wall"
	GrassBlockID                    = "minecraft:grass_block"
	GravelID                        = "minecraft:gravel"
	GrayCarpetID                    = "minecraft:gray_carpet"
	GrayDyeID                       = "minecraft:gray_dye"
	GrayShulkerBoxID                = "minecraft:gray_shulker_box"
	GrayWoolID                      = "minecraft:gray_wool"
	GreenCarpetID                   = "minecraft:green_carpet"
	GreenConcreteID                 = "minecraft:green_concrete"
	GreenDyeID                      = "minecraft:green_dye"
	GreenShulkerBoxID               = "minecraft:green_shulker_box"
	GreenStainedGlassID             = "minecraft:green_stained_glass"
	GreenTerracottaID               = "minecraft:green_terracotta"
	GreenWoolID                     = "minecraft:green_wool"
	GrindstoneID                    = "minecraft:grindstone"
	HayBlockID                      = "minecraft:hay_block"
	HeartOfTheSeaID                 = "minecraft:heart_of_the_sea"
	HeavyWeightedPressurePlateID    = "minecraft:heavy_weighted_pressure_plate"
	HoneyBlockID                    = "minecraft:honey_block"
	HoneyBottleID                   = "minecraft:honey_bottle"
	HoneycombID                     = "minecraft:honeycomb"
	HopperID                        = "minecraft:hopper"
	HopperMinecartID                = "minecraft:hopper_minecart"
	HornCoralID                     = "minecraft:horn_coral"
	HornCoralBlockID                = "minecraft:horn_coral_block"
	HornCoralFanID                  = "minecraft:horn_coral_fan"
	IceID                           = "minecraft:ice"
	InkSacID                        = "minecraft:ink_sac"
	IronAxeID                       = "minecraft:iron_axe"
	IronBarsID                      = "minecraft:iron_bars"
	IronBlockID                     = "minecraft:iron_block"
	IronBootsID                     = "minecraft:iron_boots"
	IronChestplateID                = "minecraft:iron_chestplate"
	IronDoorID                      = "minecraft:iron_door"
	IronHelmetID                    = "minecraft:iron_helmet"
	IronHoeID                       = "minecraft:iron_hoe"
	IronHorseArmorID                = "minecraft:iron_horse_armor"
	IronLeggingsID                  = "minecraft:iron_leggings"
	IronNuggetID                    = "minecraft:iron_nugget"
	IronOreID                       = "minecraft:iron_ore"
	IronPickaxeID                   = "minecraft:iron_pickaxe"
	IronShovelID                    = "minecraft:iron_shovel"
	IronTrapdoorID                  = "minecraft:iron_trapdoor"
	JukeboxID                       = "minecraft:jukebox"
	JungleBoatID                    = "minecraft:jungle_boat"
	JungleButtonID                  = "minecraft:jungle_button"
	JungleDoorID                    = "minecraft:jungle_door"
	JungleFenceID                   = "minecraft:jungle_fence"
	JungleFenceGateID               = "minecraft:jungle_fence_gate"
	JungleLeavesID                  = "minecraft:jungle_leaves"
	JungleLogID                     = "minecraft:jungle_log"
	JunglePlanksID                  = "minecraft:jungle_planks"
	JungleSaplingID                 = "minecraft:jungle_sapling"
	JungleSignID                    = "minecraft:jungle_sign"
	JungleSlabID                    = "minecraft:jungle_slab"
	JungleStairsID                  = "minecraft:jungle_stairs"
	JungleTrapdoorID                = "minecraft:jungle_trapdoor"
	JungleWoodID                    = "minecraft:jungle_wood"
	KelpID                          = "minecraft:kelp"
	LadderID                        = "minecraft:ladder"
	LanternID                       = "minecraft:lantern"
	LapisBlockID                    = "minecraft:lapis_block"
	LapisLazuliID                   = "minecraft:lapis_lazuli"
	LapisOreID                      = "minecraft:lapis_ore"
	LargeAmethystBudID              = "minecraft:large_amethyst_bud"
	LavaBucketID                    = "minecraft:lava_bucket"
	LeadID                          = "minecraft:lead"
	LeatherID                       = "minecraft:leather"
	LeatherBootsID                  = "minecraft:leather_boots"
	LeatherChestplateID             = "minecraft:leather_chestplate"
	LeatherHelmetID                 = "minecraft:leather_helmet"
	LeatherLeggingsID               = "minecraft:leather_leggings"
	LeverID                         = "minecraft:lever"
	LightBlueCandleID               = "minecraft:light_blue_candle"
	LightBlueCarpetID               = "minecraft:light_blue_carpet"
	LightBlueConcreteID             = "minecraft:light_blue_concrete"
	LightBlueDyeID                  = "minecraft:light_blue_dye"
	LightBlueShulkerBoxID           = "minecraft:light_blue_shulker_box"
	LightBlueStainedGlassID         = "minecraft:light_blue_stained_glass"
	LightBlueStainedGlassPaneID     = "minecraft:light_blue_stained_glass_pane"
	LightBlueTerracottaID           = "minecraft:light_blue_terracotta"
	LightBlueWoolID                 = "minecraft:light_blue_wool"
	LightGrayCarpetID               = "minecraft:light_gray_carpet"
	LightGrayDyeID                  = "minecraft:light_gray_dye"
	LightGrayShulkerBoxID           = "minecraft:light_gray_shulker_box"
	LightGrayTerracottaID           = "minecraft:light_gray_terracotta"
	LightGrayWoolID                 = "minecraft:light_gray_wool"
	LightWeightedPressurePlateID    = "minecraft:light_weighted_pressure_plate"
	LightningRodID                  = "minecraft:lightning_rod"
	LilacID                         = "minecraft:lilac"
	LilyOfTheValleyID               = "minecraft:lily_of_the_valley"
	LilyPadID                       = "minecraft:lily_pad"
	LimeCarpetID                    = "minecraft:lime_carpet"
	LimeConcreteID                  = "minecraft:lime_concrete"
	LimeDyeID                       = "minecraft:lime_dye"
	LimeGlazedTerracottaID          = "minecraft:lime_glazed_terracotta"
	LimeShulkerBoxID                = "minecraft:lime_shulker_box"
	LimeStainedGlassID              = "minecraft:lime_stained_glass"
	LimeStainedGlassPaneID          = "minecraft:lime_stained_glass_pane"
	LimeTerracottaID                = "minecraft:lime_terracotta"
	LimeWoolID                      = "minecraft:lime_wool"
	LodestoneID                     = "minecraft:lodestone"
	MagentaBannerID                 = "minecraft:magenta_banner"
	MagentaCarpetID                 = "minecraft:magenta_carpet"
	MagentaDyeID                    = "minecraft:magenta_dye"
	MagentaShulkerBoxID             = "minecraft:magenta_shulker_box"
	MagentaStainedGlassID           = "minecraft:magenta_stained_glass"
	MagentaStainedGlassPaneID       = "minecraft:magenta_stained_glass_pane"
	MagentaWoolID                   = "minecraft:magenta_wool"
	MagmaBlockID                    = "minecraft:magma_block"
	MagmaCreamID                    = "minecraft:magma_cream"
	MapID                           = "minecraft:map"
	MediumAmethystBudID             = "minecraft:medium_amethyst_bud"
	MelonID                         = "minecraft:melon"
	MelonSeedsID                    = "minecraft:melon_seeds"
	MelonSliceID                    = "minecraft:melon_slice"
	MilkBucketID                    = "minecraft:milk_bucket"
	MojangBannerPatternID           = "minecraft:mojang_banner_pattern"
	MossBlockID                     = "minecraft:moss_block"
	MossCarpetID                    = "minecraft:moss_carpet"
	MossyCobblestoneID              = "minecraft:mossy_cobblestone"
	MossyCobblestoneSlabID          = "minecraft:mossy_cobblestone_slab"
	MossyCobblestoneStairsID        = "minecraft:mossy_cobblestone_stairs"
	MossyCobblestoneWallID          = "minecraft:mossy_cobblestone_wall"
	MossyStoneBrickSlabID           = "minecraft:mossy_stone_brick_slab"
	MossyStoneBrickStairsID         = "minecraft:mossy_stone_brick_stairs"
	MossyStoneBrickWallID           = "minecraft:mossy_stone_brick_wall"
	MossyStoneBricksID              = "minecraft:mossy_stone_bricks"
	MushroomStemID                  = "minecraft:mushroom_stem"
	MusicDisc11ID                   = "minecraft:music_disc_11"
	MusicDisc13ID                   = "minecraft:music_disc_13"
	MusicDiscBlocksID               = "minecraft:music_disc_blocks"
	MusicDiscCatID                  = "minecraft:music_disc_cat"
	MusicDiscChirpID                = "minecraft:music_disc_chirp"
	MusicDiscFarID                  = "minecraft:music_disc_far"
	MusicDiscMallID                 = "minecraft:music_disc_mall"
	MusicDiscMellohiID              = "minecraft:music_disc_mellohi"
	MusicDiscStalID                 = "minecraft:music_disc_stal"
	MusicDiscStradID                = "minecraft:music_disc_strad"
	MusicDiscWaitID                 = "minecraft:music_disc_wait"
	MusicDiscWardID                 = "minecraft:music_disc_ward"
	MuttonID                        = "minecraft:mutton"
	MyceliumID                      = "minecraft:mycelium"
	NameTagID                       = "minecraft:name_tag"
	NautilusShellID                 = "minecraft:nautilus_shell"
	NetherBrickID                   = "minecraft:nether_brick"
	NetherBrickFenceID              = "minecraft:nether_brick_fence"
	NetherBrickSlabID               = "minecraft:nether_brick_slab"
	NetherBrickStairsID             = "minecraft:nether_brick_stairs"
	NetherBricksID                  = "minecraft:nether_bricks"
	NetherGoldOreID                 = "minecraft:nether_gold_ore"
	NetherQuartzOreID               = "minecraft:nether_quartz_ore"
	NetherStarID                    = "minecraft:nether_star"
	NetherWartID                    = "minecraft:nether_wart"
	NetherWartBlockID               = "minecraft:nether_wart_block"
	NetheriteScrapID                = "minecraft:netherite_scrap"
	NetheriteShovelID               = "minecraft:netherite_shovel"
	NetheriteSwordID                = "minecraft:netherite_sword"
	NetherrackID                    = "minecraft:netherrack"
	NoteBlockID                     = "minecraft:note_block"
	OakBoatID                       = "minecraft:oak_boat"
	OakButtonID                     = "minecraft:oak_button"
	OakFenceID                      = "minecraft:oak_fence"
	OakFenceGateID                  = "minecraft:oak_fence_gate"
	OakLeavesID                     = "minecraft:oak_leaves"
	OakLogID                        = "minecraft:oak_log"
	OakPlanksID                     = "minecraft:oak_planks"
	OakPressurePlateID              = "minecraft:oak_pressure_plate"
	OakSignID                       = "minecraft:oak_sign"
	OakSlabID                       = "minecraft:oak_slab"
	OakStairsID                     = "minecraft:oak_stairs"
	OakTrapdoorID                   = "minecraft:oak_trapdoor"
	OakWoodID                       = "minecraft:oak_wood"
	ObserverID                      = "minecraft:observer"
	ObsidianID                      = "minecraft:obsidian"
	OrangeCandleID                  = "minecraft:orange_candle"
	OrangeCarpetID                  = "minecraft:orange_carpet"
	OrangeConcreteID                = "minecraft:orange_concrete"
	OrangeDyeID                     = "minecraft:orange_dye"
	OrangeGlazedTerracottaID        = "minecraft:orange_glazed_terracotta"
	OrangeShulkerBoxID              = "minecraft:orange_shulker_box"
	OrangeStainedGlassID            = "minecraft:orange_stained_glass"
	OrangeStainedGlassPaneID        = "minecraft:orange_stained_glass_pane"
	OrangeTerracottaID              = "minecraft:orange_terracotta"
	OrangeTulipID                   = "minecraft:orange_tulip"
	OrangeWoolID                    = "minecraft:orange_wool"
	OxeyeDaisyID                    = "minecraft:oxeye_daisy"
	PackedIceID                     = "minecraft:packed_ice"
	PaintingID                      = "minecraft:painting"
	PeonyID                         = "minecraft:peony"
	PhantomMembraneID               = "minecraft:phantom_membrane"
	PinkConcreteID                  = "minecraft:pink_concrete"
	PinkDyeID                       = "minecraft:pink_dye"
	PinkShulkerBoxID                = "minecraft:pink_shulker_box"
	PinkTerracottaID                = "minecraft:pink_terracotta"
	PinkTulipID                     = "minecraft:pink_tulip"
	PinkWoolID                      = "minecraft:pink_wool"
	PistonID                        = "minecraft:piston"
	PodzolID                        = "minecraft:podzol"
	PointedDripstoneID              = "minecraft:pointed_dripstone"
	PoisonousPotatoID               = "minecraft:poisonous_potato"
	PolishedAndesiteID              = "minecraft:polished_andesite"
	PolishedAndesiteSlabID          = "minecraft:polished_andesite_slab"
	PolishedAndesiteStairsID        = "minecraft:polished_andesite_stairs"
	PolishedBasaltID                = "minecraft:polished_basalt"
	PolishedBlackstoneID            = "minecraft:polished_blackstone"
	PolishedBlackstoneBrickSlabID   = "minecraft:polished_blackstone_brick_slab"
	PolishedBlackstoneBrickStairsID = "minecraft:polished_blackstone_brick_stairs"
	PolishedBlackstoneBrickWallID   = "minecraft:polished_blackstone_brick_wall"
	PolishedBlackstoneBricksID      = "minecraft:polished_blackstone_bricks"
	PolishedBlackstoneButtonID      = "minecraft:polished_blackstone_button"
	PolishedBlackstoneSlabID        = "minecraft:polished_blackstone_slab"
	PolishedBlackstoneStairsID      = "minecraft:polished_blackstone_stairs"
	PolishedBlackstoneWallID        = "minecraft:polished_blackstone_wall"
	PolishedDeepslateID             = "minecraft:polished_deepslate"
	PolishedDeepslateSlabID         = "minecraft:polished_deepslate_slab"
	PolishedDeepslateStairsID       = "minecraft:polished_deepslate_stairs"
	PolishedDeepslateWallID         = "minecraft:polished_deepslate_wall"
	PolishedDioriteID               = "minecraft:polished_diorite"
	PolishedDioriteSlabID           = "minecraft:polished_diorite_slab"
	PolishedDioriteStairsID         = "minecraft:polished_diorite_stairs"
	PolishedGraniteID               = "minecraft:polished_granite"
	PolishedGraniteSlabID           = "minecraft:polished_granite_slab"
	PolishedGraniteStairsID         = "minecraft:polished_granite_stairs"
	PoppedChorusFruitID             = "minecraft:popped_chorus_fruit"
	PotatoID                        = "minecraft:potato"
	PowderSnowBucketID              = "minecraft:powder_snow_bucket"
	PoweredRailID                   = "minecraft:powered_rail"
	PrismarineID                    = "minecraft:prismarine"
	PrismarineBrickSlabID           = "minecraft:prismarine_brick_slab"
	PrismarineBrickStairsID         = "minecraft:prismarine_brick_stairs"
	PrismarineBricksID              = "minecraft:prismarine_bricks"
	PrismarineShardID               = "minecraft:prismarine_shard"
	PrismarineSlabID                = "minecraft:prismarine_slab"
	PrismarineStairsID              = "minecraft:prismarine_stairs"
	PrismarineWallID                = "minecraft:prismarine_wall"
	PumpkinID                       = "minecraft:pumpkin"
	PumpkinSeedsID                  = "minecraft:pumpkin_seeds"
	PurpleCarpetID                  = "minecraft:purple_carpet"
	PurpleConcreteID                = "minecraft:purple_concrete"
	PurpleConcretePowderID          = "minecraft:purple_concrete_powder"
	PurpleDyeID                     = "minecraft:purple_dye"
	PurpleShulkerBoxID              = "minecraft:purple_shulker_box"
	PurpleStainedGlassID            = "minecraft:purple_stained_glass"
	PurpleTerracottaID              = "minecraft:purple_terracotta"
	PurpleWoolID                    = "minecraft:purple_wool"
	PurpurBlockID                   = "minecraft:purpur_block"
	PurpurPillarID                  = "minecraft:purpur_pillar"
	PurpurSlabID                    = "minecraft:purpur_slab"
	PurpurStairsID                  = "minecraft:purpur_stairs"
	QuartzID                        = "minecraft:quartz"
	QuartzBlockID                   = "minecraft:quartz_block"
	QuartzBricksID                  = "minecraft:quartz_bricks"
	QuartzPillarID                  = "minecraft:quartz_pillar"
	QuartzSlabID                    = "minecraft:quartz_slab"
	QuartzStairsID                  = "minecraft:quartz_stairs"
	RabbitFootID                    = "minecraft:rabbit_foot"
	RailID                          = "minecraft:rail"
	RawCopperID                     = "minecraft:raw_copper"
	RawGoldID                       = "minecraft:raw_gold"
	RawIronID                       = "minecraft:raw_iron"
	RawIronBlockID                  = "minecraft:raw_iron_block"
	RedBannerID                     = "minecraft:red_banner"
	RedCarpetID                     = "minecraft:red_carpet"
	RedDyeID                        = "minecraft:red_dye"
	RedGlazedTerracottaID           = "minecraft:red_glazed_terracotta"
	RedMushroomID                   = "minecraft:red_mushroom"
	RedMushroomBlockID              = "minecraft:red_mushroom_block"
	RedNetherBrickSlabID            = "minecraft:red_nether_brick_slab"
	RedNetherBrickStairsID          = "minecraft:red_nether_brick_stairs"
	RedNetherBrickWallID            = "minecraft:red_nether_brick_wall"
	RedNetherBricksID               = "minecraft:red_nether_bricks"
	RedSandID                       = "minecraft:red_sand"
	RedSandstoneID                  = "minecraft:red_sandstone"
	RedSandstoneSlabID              = "minecraft:red_sandstone_slab"
	RedSandstoneStairsID            = "minecraft:red_sandstone_stairs"
	RedSandstoneWallID              = "minecraft:red_sandstone_wall"
	RedShulkerBoxID                 = "minecraft:red_shulker_box"
	RedStainedGlassID               = "minecraft:red_stained_glass"
	RedStainedGlassPaneID           = "minecraft:red_stained_glass_pane"
	RedTerracottaID                 = "minecraft:red_terracotta"
	RedTulipID                      = "minecraft:red_tulip"
	RedstoneID                      = "minecraft:redstone"
	RedstoneBlockID                 = "minecraft:redstone_block"
	RedstoneLampID                  = "minecraft:redstone_lamp"
	RedstoneOreID                   = "minecraft:redstone_ore"
	RedstoneTorchID                 = "minecraft:redstone_torch"
	RepeaterID                      = "minecraft:repeater"
	RespawnAnchorID                 = "minecraft:respawn_anchor"
	RootedDirtID                    = "minecraft:rooted_dirt"
	RoseBushID                      = "minecraft:rose_bush"
	RottenFleshID                   = "minecraft:rotten_flesh"
	SaddleID                        = "minecraft:saddle"
	SandstoneID                     = "minecraft:sandstone"
	SandstoneSlabID                 = "minecraft:sandstone_slab"
	SandstoneStairsID               = "minecraft:sandstone_stairs"
	SandstoneWallID                 = "minecraft:sandstone_wall"
	ScaffoldingID                   = "minecraft:scaffolding"
	ScuteID                         = "minecraft:scute"
	SeaLanternID                    = "minecraft:sea_lantern"
	SeaPickleID                     = "minecraft:sea_pickle"
	SeagrassID                      = "minecraft:seagrass"
	ShearsID                        = "minecraft:shears"
	ShroomlightID                   = "minecraft:shroomlight"
	ShulkerShellID                  = "minecraft:shulker_shell"
	SkeletonSkullID                 = "minecraft:skeleton_skull"
	SkullID                         = "minecraft:skull"
	SkullBannerPatternID            = "minecraft:skull_banner_pattern"
	SlimeBallID                     = "minecraft:slime_ball"
	SlimeBlockID                    = "minecraft:slime_block"
	SmallAmethystBudID              = "minecraft:small_amethyst_bud"
	SmallDripleafID                 = "minecraft:small_dripleaf"
	SmallFireballID                 = "minecraft:small_fireball"
	SmoothBasaltID                  = "minecraft:smooth_basalt"
	SmoothSandstoneStairsID         = "minecraft:smooth_sandstone_stairs"
	SmoothStoneID                   = "minecraft:smooth_stone"
	SmoothStoneSlabID               = "minecraft:smooth_stone_slab"
	SnowID                          = "minecraft:snow"
	SnowBlockID                     = "minecraft:snow_block"
	SnowballID                      = "minecraft:snowball"
	SoulLanternID                   = "minecraft:soul_lantern"
	SoulSandID                      = "minecraft:soul_sand"
	SoulSoilID                      = "minecraft:soul_soil"
	SoulTorchID                     = "minecraft:soul_torch"
	SpectralArrowID                 = "minecraft:spectral_arrow"
	SpiderEyeID                     = "minecraft:spider_eye"
	SplashPotionID                  = "minecraft:splash_potion"
	SpongeID                        = "minecraft:sponge"
	SporeBlossomID                  = "minecraft:spore_blossom"
	SpruceBoatID                    = "minecraft:spruce_boat"
	SpruceButtonID                  = "minecraft:spruce_button"
	SpruceDoorID                    = "minecraft:spruce_door"
	SpruceFenceID                   = "minecraft:spruce_fence"
	SpruceFenceGateID               = "minecraft:spruce_fence_gate"
	SpruceLeavesID                  = "minecraft:spruce_leaves"
	SpruceLogID                     = "minecraft:spruce_log"
	SprucePlanksID                  = "minecraft:spruce_planks"
	SpruceSaplingID                 = "minecraft:spruce_sapling"
	SpruceSignID                    = "minecraft:spruce_sign"
	SpruceSlabID                    = "minecraft:spruce_slab"
	SpruceStairsID                  = "minecraft:spruce_stairs"
	SpruceTrapdoorID                = "minecraft:spruce_trapdoor"
	SpruceWoodID                    = "minecraft:spruce_wood"
	SpyglassID                      = "minecraft:spyglass"
	StickID                         = "minecraft:stick"
	StickyPistonID                  = "minecraft:sticky_piston"
	StoneAxeID                      = "minecraft:stone_axe"
	StoneBrickSlabID                = "minecraft:stone_brick_slab"
	StoneBrickStairsID              = "minecraft:stone_brick_stairs"
	StoneBrickWallID                = "minecraft:stone_brick_wall"
	StoneBricksID                   = "minecraft:stone_bricks"
	StoneButtonID                   = "minecraft:stone_button"
	StonePressurePlateID            = "minecraft:stone_pressure_plate"
	StoneSlabID                     = "minecraft:stone_slab"
	StoneStairsID                   = "minecraft:stone_stairs"
	StonecutterID                   = "minecraft:stonecutter"
	StringID                        = "minecraft:string"
	StrippedBirchLogID              = "minecraft:stripped_birch_log"
	StrippedCrimsonHyphaeID         = "minecraft:stripped_crimson_hyphae"
	StrippedCrimsonStemID           = "minecraft:stripped_crimson_stem"
	StrippedDarkOakLogID            = "minecraft:stripped_dark_oak_log"
	StrippedJungleLogID             = "minecraft:stripped_jungle_log"
	StrippedOakLogID                = "minecraft:stripped_oak_log"
	StrippedSpruceLogID             = "minecraft:stripped_spruce_log"
	StrippedWarpedHyphaeID          = "minecraft:stripped_warped_hyphae"
	StrippedWarpedStemID            = "minecraft:stripped_warped_stem"
	SugarID                         = "minecraft:sugar"
	SugarCaneID                     = "minecraft:sugar_cane"
	SunflowerID                     = "minecraft:sunflower"
	SuspiciousStewID                = "minecraft:suspicious_stew"
	SweetBerriesID                  = "minecraft:sweet_berries"
	TargetID                        = "minecraft:target"
	TerracottaID                    = "minecraft:terracotta"
	TippedArrowID                   = "minecraft:tipped_arrow"
	TntID                           = "minecraft:tnt"
	TorchID                         = "minecraft:torch"
	TotemOfUndyingID                = "minecraft:totem_of_undying"
	TridentID                       = "minecraft:trident"
	TripwireHookID                  = "minecraft:tripwire_hook"
	TropicalFishBucketID            = "minecraft:tropical_fish_bucket"
	TubeCoralID                     = "minecraft:tube_coral"
	TubeCoralBlockID                = "minecraft:tube_coral_block"
	TubeCoralFanID                  = "minecraft:tube_coral_fan"
	TuffID                          = "minecraft:tuff"
	TwistingVinesID                 = "minecraft:twisting_vines"
	VineID                          = "minecraft:vine"
	WarpedButtonID                  = "minecraft:warped_button"
	WarpedDoorID                    = "minecraft:warped_door"
	WarpedFenceID                   = "minecraft:warped_fence"
	WarpedFenceGateID               = "minecraft:warped_fence_gate"
	WarpedFungusID                  = "minecraft:warped_fungus"
	WarpedFungusOnAStickID          = "minecraft:warped_fungus_on_a_stick"
	WarpedHyphaeID                  = "minecraft:warped_hyphae"
	WarpedNyliumID                  = "minecraft:warped_nylium"
	WarpedPlanksID                  = "minecraft:warped_planks"
	WarpedPressurePlateID           = "minecraft:warped_pressure_plate"
	WarpedRootsID                   = "minecraft:warped_roots"
	WarpedSignID                    = "minecraft:warped_sign"
	WarpedSlabID                    = "minecraft:warped_slab"
	WarpedStairsID                  = "minecraft:warped_stairs"
	WarpedStemID                    = "minecraft:warped_stem"
	WarpedTrapdoorID                = "minecraft:warped_trapdoor"
	WarpedWartBlockID               = "minecraft:warped_wart_block"
	WaterBucketID                   = "minecraft:water_bucket"
	WaxedCutCopperID                = "minecraft:waxed_cut_copper"
	WaxedCutCopperSlabID            = "minecraft:waxed_cut_copper_slab"
	WaxedCutCopperStairsID          = "minecraft:waxed_cut_copper_stairs"
	WeepingVinesID                  = "minecraft:weeping_vines"
	WetSpongeID                     = "minecraft:wet_sponge"
	WheatSeedsID                    = "minecraft:wheat_seeds"
	WhiteBannerID                   = "minecraft:white_banner"
	WhiteBedID                      = "minecraft:white_bed"
	WhiteCarpetID                   = "minecraft:white_carpet"
	WhiteConcreteID                 = "minecraft:white_concrete"
	WhiteDyeID                      = "minecraft:white_dye"
	WhiteGlazedTerracottaID         = "minecraft:white_glazed_terracotta"
	WhiteShulkerBoxID               = "minecraft:white_shulker_box"
	WhiteStainedGlassID             = "minecraft:white_stained_glass"
	WhiteTerracottaID               = "minecraft:white_terracotta"
	WhiteTulipID                    = "minecraft:white_tulip"
	WhiteWoolID                     = "minecraft:white_wool"
	WitherRoseID                    = "minecraft:wither_rose"
	WitherSkeletonSkullID           = "minecraft:wither_skeleton_skull"
	WitherSkullID                   = "minecraft:wither_skull"
	YellowBedID                     = "minecraft:yellow_bed"
	YellowCarpetID                  = "minecraft:yellow_carpet"
	YellowConcreteID                = "minecraft:yellow_concrete"
	YellowDyeID                     = "minecraft:yellow_dye"
	YellowGlazedTerracottaID        = "minecraft:yellow_glazed_terracotta"
	YellowShulkerBoxID              = "minecraft:yellow_shulker_box"
	YellowStainedGlassID            = "minecraft:yellow_stained_glass"
	YellowStainedGlassPaneID        = "minecraft:yellow_stained_glass_pane"
	YellowTerracottaID              = "minecraft:yellow_terracotta"
	YellowWoolID                    = "minecraft:yellow_wool"
	ZombieHeadID                    = "minecraft:zombie_head"

	ItemID = "minecraft:item"

	AirID          = "minecraft:air" // Blocks IDs
	BedID          = "minecraft:bed"
	CactusID       = "minecraft:cactus"
	FallingBlockID = "minecraft:falling_block"
	GraniteID      = "minecraft:granite"
	GrassID        = "minecraft:grass"
	MobSpawnerID   = "minecraft:mob_spawner"
	PoppyID        = "minecraft:poppy"
	SandID         = "minecraft:sand"
	StoneID        = "minecraft:stone"

	AppleID              = "minecraft:apple"
	BookID               = "minecraft:book"
	BreadID              = "minecraft:bread"
	CookedSalmonID       = "minecraft:cooked_salmon"
	DiamondChestplateID  = "minecraft:diamond_chestplate"
	EnchantedBookID      = "minecraft:enchanted_book"
	ExperienceOrbID      = "minecraft:experience_orb"
	GunpowderID          = "minecraft:gunpowder"
	IronIngotID          = "minecraft:iron_ingot"
	IronSwordID          = "minecraft:iron_sword"
	FeatherID            = "minecraft:feather"
	GlassBottleID        = "minecraft:glass_bottle"
	OakSaplingID         = "minecraft:oak_sapling"
	PaperID              = "minecraft:paper"
	PotionID             = "minecraft:potion"
	PrismarineCrystalsID = "minecraft:prismarine_crystals"
	WheatID              = "minecraft:wheat"

	SignID         = "minecraft:sign"
	WritableBookID = "minecraft:writable_book"
	WrittenBookID  = "minecraft:written_book"

	BoatID          = "minecraft:boat" // Transport IDs
	ChestMinecartID = "minecraft:chest_minecart"
	MinecartID      = "minecraft:minecart"

	BannerID       = "minecraft:banner" // Block entity IDs
	BarrelID       = "minecraft:barrel"
	BeehiveID      = "minecraft:beehive"
	BellID         = "minecraft:bell"
	ChestID        = "minecraft:chest"
	DropperID      = "minecraft:dropper"
	DispenserID    = "minecraft:dispenser"
	FurnaceID      = "minecraft:furnace"
	LecternID      = "minecraft:lectern"
	ShulkerBoxID   = "minecraft:shulker_box"
	SmokerID       = "minecraft:smoker"
	TrappedChestID = "minecraft:trapped_chest"

	GlowItemFrameID = "minecraft:glow_item_frame"
	ItemFrameID     = "minecraft:item_frame"

	AllayID           = "minecraft:allay" // Entities IDs
	AxolotlID         = "minecraft:axolotl"
	BatID             = "minecraft:bat"
	BeeID             = "minecraft:bee"
	BlazeID           = "minecraft:blaze"
	CatID             = "minecraft:cat"
	CaveSpiderID      = "minecraft:cave_spider"
	ChickenID         = "minecraft:chicken"
	CodID             = "minecraft:cod"
	CowID             = "minecraft:cow"
	CreeperID         = "minecraft:creeper"
	DolphinID         = "minecraft:dolphin"
	DonkeyID          = "minecraft:donkey"
	DrownedID         = "minecraft:drowned"
	ElderGuardianID   = "minecraft:elder_guardian"
	EnderDragonID     = "minecraft:ender_dragon"
	EndermanID        = "minecraft:enderman"
	EndermiteID       = "minecraft:endermite"
	EvokerID          = "minecraft:evoker"
	FoxID             = "minecraft:fox"
	FrogID            = "minecraft:frog"
	GhastID           = "minecraft:ghast"
	GiantID           = "minecraft:giant"
	GlowSquidID       = "minecraft:glow_squid"
	GoatID            = "minecraft:goat"
	GuardianID        = "minecraft:guardian"
	HoglinID          = "minecraft:hoglin"
	HorseID           = "minecraft:horse"
	HuskID            = "minecraft:husk"
	IllusionerID      = "minecraft:illusioner"
	IronGolemID       = "minecraft:iron_golem"
	LlamaID           = "minecraft:llama"
	MagmaCubeID       = "minecraft:magma_cube"
	MooshroomID       = "minecraft:mooshroom"
	MuleID            = "minecraft:mule"
	OcelotID          = "minecraft:ocelot"
	PandaID           = "minecraft:panda"
	ParrotID          = "minecraft:parrot"
	PhantomID         = "minecraft:phantom"
	PigID             = "minecraft:pig"
	PiglinID          = "minecraft:piglin"
	PiglinBruteID     = "minecraft:piglin_brute"
	PillagerID        = "minecraft:pillager"
	PolarBearID       = "minecraft:polar_bear"
	PufferfishID      = "minecraft:pufferfish"
	RabbitID          = "minecraft:rabbit"
	RavagerID         = "minecraft:ravager"
	SalmonID          = "minecraft:salmon"
	SheepID           = "minecraft:sheep"
	ShulkerID         = "minecraft:shulker"
	SilverfishID      = "minecraft:silverfish"
	SkeletonID        = "minecraft:skeleton"
	SkeletonHorseID   = "minecraft:skeleton_horse"
	SlimeID           = "minecraft:slime"
	SnowGolemID       = "minecraft:snow_golem"
	SpiderID          = "minecraft:spider"
	StriderID         = "minecraft:strider"
	SquidID           = "minecraft:squid"
	StrayID           = "minecraft:stray"
	TadpoleID         = "minecraft:tadpole"
	TraderLlamaID     = "minecraft:trader_llama"
	TropicalFishID    = "minecraft:tropical_fish"
	TurtleID          = "minecraft:turtle"
	VexID             = "minecraft:vex"
	VillagerID        = "minecraft:villager"
	VindicatorID      = "minecraft:vindicator"
	WanderingTraderID = "minecraft:wandering_trader"
	WardenID          = "minecraft:warden"
	WitchID           = "minecraft:witch"
	WitherID          = "minecraft:wither"
	WitherSkeletonID  = "minecraft:wither_skeleton"
	WolfID            = "minecraft:wolf"
	ZoglinID          = "minecraft:zoglin"
	ZombieID          = "minecraft:zombie"
	ZombieHorseID     = "minecraft:zombie_horse"
	ZombieVillagerID  = "minecraft:zombie_villager"
	ZombifiedPiglinID = "minecraft:zombified_piglin"
)

func (i ID) IsTransport() bool {
	return i == BoatID ||
		i == MinecartID
}

func (i ID) IsEntity() bool {
	return i == GlowItemFrameID ||
		i == ItemFrameID ||
		i == AllayID ||
		i == AxolotlID ||
		i == BatID ||
		i == BeeID ||
		i == BlazeID ||
		i == CatID ||
		i == CaveSpiderID ||
		i == ChickenID ||
		i == CodID ||
		i == CowID ||
		i == CreeperID ||
		i == DolphinID ||
		i == DonkeyID ||
		i == DrownedID ||
		i == ElderGuardianID ||
		i == EnderDragonID ||
		i == EndermanID ||
		i == EndermiteID ||
		i == EvokerID ||
		i == FoxID ||
		i == FrogID ||
		i == GhastID ||
		i == GiantID ||
		i == GlowSquidID ||
		i == GoatID ||
		i == GuardianID ||
		i == HoglinID ||
		i == HorseID ||
		i == HuskID ||
		i == IllusionerID ||
		i == IronGolemID ||
		i == LlamaID ||
		i == MagmaCubeID ||
		i == MooshroomID ||
		i == MuleID ||
		i == OcelotID ||
		i == PandaID ||
		i == ParrotID ||
		i == PhantomID ||
		i == PigID ||
		i == PiglinID ||
		i == PiglinBruteID ||
		i == PillagerID ||
		i == PolarBearID ||
		i == PufferfishID ||
		i == RabbitID ||
		i == RavagerID ||
		i == SalmonID ||
		i == SheepID ||
		i == ShulkerID ||
		i == SilverfishID ||
		i == SkeletonID ||
		i == SkeletonHorseID ||
		i == SlimeID ||
		i == SnowGolemID ||
		i == SpiderID ||
		i == StriderID ||
		i == SquidID ||
		i == StrayID ||
		i == TadpoleID ||
		i == TraderLlamaID ||
		i == TropicalFishID ||
		i == TurtleID ||
		i == VexID ||
		i == VillagerID ||
		i == VindicatorID ||
		i == WanderingTraderID ||
		i == WardenID ||
		i == WitchID ||
		i == WitherID ||
		i == WitherSkeletonID ||
		i == WolfID ||
		i == ZoglinID ||
		i == ZombieID ||
		i == ZombieHorseID ||
		i == ZombieVillagerID ||
		i == ZombifiedPiglinID
}
